### ISSUE TITLE
Visualize "dirty" packages of the conan cache in the vsc-conan-explorer

### ISSUE THREAD

**Issue by Pravi1206** [afri-bit/vsconan#10]
Creating own conan packages may result in dirty packages as there might be bugs etc in the development chain. They are marked as "dirty".

**Goal:** Visualize dirty packes in the conan explorer (maybe with a red icon)

**Comment by afri-bit** [comment]
Hi @Pravi1206,
the feature is now implemented, and can be tested in the develop branch.
As for now I will close this issue.
