### ISSUE TITLE
After vsconan loaded, 1st conan command triggers `WARN: Migration: Updating settings.yml`

### ISSUE THREAD

**Issue by SpaceIm** [afri-bit/vsconan#12]
see https://github.com/conan-io/conan/issues/11259

**Comment by afri-bit** [comment]
Hi @SpaceIm,
I was able to reproduce the issue that you reported, **only** if I have different conan version installed in a different python interpreter/environment. Could you please check the conan version that you installed in the interpreter for the VSConan extension (the python interpreter can be configured under `~/.vsconan/config.json`) and in the CLI that you use, if the version is different.

Following details to reproduce the issue from my side:
- Python version: 3.9.12
- Virtual environment with conan version 1.47.0
- Virtual environment with conan version 1.48.0
- Virtual environment with conan version 1.48.1
So if I execute any command (`conan --version` or only `conan`, basically anything, or using the VSConan extension) using different conan version, it will always create a new settings file.
The extension basically only executes conan CLI in the background based on the python interpreter that is configured in the `~/.vsconan/config.json`.
I hope, this helps you a bit. Meanwhile I will try to find out from my side, if there is anything I can do about this issue.
