### ISSUE TITLE
Managing editable packages

### ISSUE THREAD

**Issue by chausner** [afri-bit/vsconan#13]
First of all, thanks a lot for writing this extension! VS Code has been lacking a good Conan extension but this one already looks very promising and it's just the first release.

I'd like to suggest a feature to create/list/delete editable packages. Managing editable packages is rather cumbersome to do on the command-line because you have to type a lot. It would be great if the extension could make that easier by

- showing a list of all packages that are currently in editable mode
- offering an option to make the package in the workspace editable (supporting `conanlayout.ini` would be a plus)
- offering an option to remove any package from the editable list

**Comment by afri-bit** [comment]
Hi @chausner,
many thanks for your feedback, I am happy to hear that the extension can help the community and improve their efficiency, I will try my best to keep this always up to date and add more features.

Thanks for your request, I will take this into one of the project, and set it to do, I think I missed this `editable` command during the concept phase :D

**Comment by afri-bit** [comment]
Hi @chausner,
the editable package manager is implemented now.
Currently only supports the basic necessary options:
- List the editable package recipe
![image](https://user-images.githubusercontent.com/20866800/171028633-5e7f083d-71d6-4832-863c-4dccee44d1df.png)
- Remove from Explorer or using VS Code command
![image](https://user-images.githubusercontent.com/20866800/171028753-026e7800-25fa-4205-8cd7-5cd7c0791613.png)
- Add conan workspace to editable
To add, there are some sequential steps to be done, such as inserting user, channel and layout (currently no dropdown option for this - potential feature)

As for now I will close this ticket :) I will make the release soon.

**Comment by chausner** [comment]
> the editable package manager is implemented now.

Awesome, thanks for the quick action! I'll give it a go when it gets released with the next version.

**Comment by afri-bit** [comment]
New version is already released ;)
