### ISSUE TITLE
Support non-pip conan installation

### ISSUE THREAD

**Issue by chausner** [afri-bit/vsconan#14]
The extension currently fails to function if Conan has been installed using one of the [alternative installers](https://conan.io/downloads.html), i.e. not as a pip package. E.g. on my system, Conan is at `C:\Program Files\Conan\conan\conan.exe` and is in the PATH but a command like `python -m conans` does not work.

If there are technical reasons why a pip installation is required and alternative installers cannot be supported, I suggest to at least make that fact clear in the README and ideally showing a more helpful error message when the pip package cannot be found.

**Comment by afri-bit** [comment]
Thanks for the input.
Basically there is no technical limitation and problem about using alternative installation, I only implemented python interpreter based on common usage of conan, and it was the initial implementation (kinda of brute force style).
And the Conan API class was badly implemented, but now its changed in the develop branch, it makes even easier to implement this option using the conan executable directly.

What I am going to with this, is to provide option in the settings.json to switch between python and conan executable.

**Comment by chausner** [comment]
> What I am going to with this, is to provide option in the settings.json to switch between python and conan executable.

Great, thanks! Ideal IMO would be if the extension chose appropriate settings automatically if the user has not configured it explicitly, e.g.:
- if "conan" is on the PATH, use it, else fall back to `python -m conans`

**Comment by afri-bit** [comment]
I would say the requested feature is already implemented. I tested it with conan alternative installation, in this executable in windows environment.
Feel free to try it, currently only available in the feature branch https://github.com/afri-bit/vsconan/tree/feature/%2314_support-non-pip-conan-installation

You have to configure the VS Code `settings.json`
![image](https://user-images.githubusercontent.com/20866800/170111358-434f2230-429c-490a-9a81-78516b443521.png)

If we are happy about that, I will close this ticket and merge it to develop branch.

**Comment by chausner** [comment]
Cool, that was quick!

> That could be working, but I prefer to give flexibility to the user, so if you have multiple conan installed on your pc, you can switch the conan executable within the VS Code instead of struggling with environment variable.

Yes, I agree with you on giving users the option but I think we could have the best of both worlds, i.e. if a user only has `conan` in PATH but not installed as a pip package, or the other way round, the extension could be smart enough to choose the right mode without requiring the user to set anything in the settings.

For example, `conanExecutionMode` could have a third option "auto" which is the default setting. In auto mode, the extension could pick whatever mode works on a user's machine. Advanced users would still have the ability to override and enforce one particular mode, and for new users it would remove one potential hurdle from getting the extension working.

**Comment by afri-bit** [comment]
Thats a great idea.
I will create a separate ticket for this topic.

As for now I will leave this implementation as it is, at least I think I will set the execution mode to `conanExecutable` as default, since even someone installs conan using pip, he/she can use conan using simple command `conan`.

**Comment by afri-bit** [comment]
#15
