### ISSUE TITLE
Support environment variables set in .bashrc

### ISSUE THREAD

**Issue by chausner-audeering** [afri-bit/vsconan#16]
I am using Ubuntu 20.04 and have customized my `CONAN_USER_HOME` variable in my bash profile `.bashrc`. Unfortunately, the extension does not load the bash profile when it invokes conan commands, thus conan uses the default user home and does not find my profiles.

I am not sure if it is feasible for the extension to automatically run conan in the context of my bash profile. If not, another solution could be to allow setting arbitrary environment variables in an extension setting.

**Comment by chausner-audeering** [comment]
For now, I have found a workaround by creating a bash script that loads my `.bashrc`
```bash
#!/bin/bash
source ~/.bashrc
conan "$@"
```
and specifying this as the conan executable.

**Comment by afri-bit** [comment]
Hi @chausner-audeering 
just to make sure once again, did you start the vs code from the terminal or over the GUI? If you set the `CONAN_USER_HOME ` in `.bashrc` you should start the VS code from terminal in order to have the environment variables that are configured in `.bashrc`.

**Comment by chausner-audeering** [comment]
Thanks for that hint. I start VS Code via the Ubuntu Launcher, not via the terminal. Requiring to run from a terminal would be very cumbersome, tough, I prefer the workaround with the bash wrapper around conan in that case.
