### ISSUE TITLE
Dependency treeview from a conan recipe

### ISSUE THREAD

**Issue by afri-bit** [afri-bit/vsconan#25]
Provide a dependency treeview from the conan recipe in the workspace.

The treeview in here is meant the treeview from VS Code on the activity bar.

**Comment by zlacelle** [comment]
+1, it would be great to see a png from "conan info -g graph.dot . && dot -Tpng graph.dot > graph.png" per package!

**Comment by afri-bit** [comment]
> +1, it would be great to see a png from "conan info -g graph.dot . && dot -Tpng graph.dot > graph.png" per package!

This feature is also in my bucket list. 
But this ticket is just meant to see the dependencies on left side of the VS code from the current workspace, not in a picture.

I will create a new issue for this.

Thanks for your feedback

**Comment by afri-bit** [comment]
@zlacelle Please take a look at #29

**Comment by afri-bit** [comment]
Closing for clean up
