### ISSUE TITLE
Add conan commands to status bar

### ISSUE THREAD

**Issue by zlacelle** [afri-bit/vsconan#27]
It would be great if, like the CMake extension, you could add buttons to automatically run "conan install", "conan build", and "conan create".

It would also be great to be able to select different profiles to run from a menu here (also like CMake) so that we could easily switch from debug to release, cross compiling, etc.

Nice extension btw!

**Comment by afri-bit** [comment]
Thanks for your feedback.

I think the feature that you are requesting regarding `conan build` and  other conan commands can be configured using the JSON files. Please check the [README.md](https://github.com/afri-bit/vsconan/blob/main/README.md)  at the last section with the JSON format. Let me know, if this is what you are looking for.

The debug, release, can be configured using the JSON file.

**Comment by afri-bit** [comment]
So basically if you have this JSON file, you can call the VS Code command e.g. `VSConan: Create` and it will parse the JSON file and list all the configuration that you have in the JSON file. So you can have multiple configurations for `conan create` and other conan commands with build type release or debug, profile, user, channel and other arguments, that you need to put into the command.

**Comment by afri-bit** [comment]
I see.
I will take a look, what I can do :) It should be not that hard to implement.

**Comment by afri-bit** [comment]
Closing for clean up
