### ISSUE TITLE
show conan remote packages, set package editable

### ISSUE THREAD

**Issue by imanSaberi** [afri-bit/vsconan#37]
1. Load and view implementation of Conan packages for selected items in Conan Remote. “vsconan.explorer.treeview.remote.item.selected” is not implemented. You can load all available packages from the repo using the command “conan search “*” -r=conancenter” or other repos.

2. Implementation of the change package in editable. It would be good if you could change the package to editable.
'Conan editable, add "path" "package name""
Path and package name sould be inserted.

**Comment by afri-bit** [comment]
Hi @imanSaberi 

thanks for using my extension and providing this feedback.

Are you using the extension for conan2 or conan1? As the latest release, I have to admit there are some missing features for conan2.

The topic number 1. -> If i am not mistaken, it should be implementeed already.

The topic number 2. -> needs to be implemented for conan2

Sorry for the late reply, I was in vacation and then so much work, but i will always try to find time to continue  this extension :) I hope you are still willing to use the extension and it can help you with your work! Your feedback is really appreciated :)

PS: Pull request can be also considered :)

**Comment by afri-bit** [comment]
Hi @imanSaberi,
I splitted this issue into two different issues #41 and #42.
Therefore I will close this issue. To track the issues please follow the referenced issues I created.
