### ISSUE TITLE
Whitespaces not supported in workspace names

### ISSUE THREAD

**Issue by torsknod-the-caridian** [afri-bit/vsconan#38]
Whitespaces are not supported in workspace names.

`vsconan/src/conans/conan/commandBuilder.ts` creates the  `cmd` as an array, but then does a `join`, concatenating it to a string:
```typescript
 public override buildCommandCreate(wsPath: string, cfg: ConfigCommandCreate): string | undefined {
        // Initialized the command in array of string. Later on will be converted to plain string.
        let cmd: Array<string> = [];

        cmd.push("create");

        // One of mandatory attributes is the path to the conanfile.py
        // If this is empty the whole command build process will be cancelled.
        if (cfg.conanRecipe !== "" && cfg.conanRecipe !== undefined) {
            cmd.push(utils.workspace.getAbsolutePathFromWorkspace(wsPath, cfg.conanRecipe));
        }
        else {
            return undefined;
        }

        ...

        return cmd.join(" ");
    }
```

`vsconan/src/utils/utils.ts` has the whole `cmd` as `string`, instead of an array, what https://nodejs.org/api/child_process.html#child_processspawncommand-args-options appaerently would support.

```typescript
export async function executeCommand(cmd: string, channel: vscode.OutputChannel) {
            // const exec = util.promisify(require('child_process').exec);
            // const { stdout, stderr } = await spawn(cmd);
            channel.show();

            const ls = spawn(cmd, [], { shell: true });
```

**Comment by afri-bit** [comment]
hi @torsknod-the-caridian,

thanks for using my extension and for providing input.
I will take a look at this issue and come back to you.

**Comment by afri-bit** [comment]
@torsknod-the-caridian 
The issue has been resolved in the latest release https://github.com/afri-bit/vsconan/releases/tag/v1.1.0 

To get the feature, please update the extension to the latest release.

Thanks again for your issue report.
In case of any further issues, please don't hesitate to open another issue.
