### ISSUE TITLE
BuildEnv not working on Windows

### ISSUE THREAD

**Issue by schwaerz** [afri-bit/vsconan#47]
Not sure whether this is supposed to work.

However: I tried using the BuildEnv button on a Windows machine, running VSCode on Windows.
Something is happening after pressing the button. No error is reported.

However the BuildEnv will not get activated.

Please note that we are using some specific settings wrt to the build env creation when calling conan:
```
                "args": [
                    "--conf:build tools.microsoft.bash:active=true",
                    "--conf:build tools.microsoft.bash:path=bash.exe",
                    "--conf:build tools.microsoft.bash:subsystem=msys2"
                ]
```

Effectively that creates the following two files:
```
conanbuild.bat
conanrun.sh
```

Not sure how VSConan will find the correct file to set up the environment.

**Comment by afri-bit** [comment]
@schwaerz 
Thanks for the issue report, I will take a look at this issue and test it locally as soon as possible.
I don't have a windows machine with me right now unfortunately.

**Comment by schwaerz** [comment]
@afri-bit Thanks for the swift response.
Actually I think I found the root cause on my end (but forgot to update this ticket, sorry for that). I have telemetry disabled in VSCode. But with telemetry disabled the python plugin won't do the environment variable distribution. See: https://github.com/microsoft/vscode-python/issues/24459#issuecomment-2483652115

Therefore I believe this ticket can be closed as a non-issue. Maybe it could be mentioned somewhere in the documentation?

**Comment by afri-bit** [comment]
@schwaerz
glad to hear you found the root cause of the problem :) Thanks for letting me know.

I will write it down and put it in the documentation on the next release.
